### ISSUE TITLE
juju config-changed hook causes service to stop

### ISSUE THREAD

**Issue by paulgear** [ubuntu-core/serial-vault-charm#1]
When upgrading the juju controller running serial-vault-partners today, we encountered some alerts from the haproxy and apache-sign charms which I traced back to snap.serial-vault.serial-vault.service being down.  When I checked the logs, I found systemctl complaining that the service was being restarted too quickly.

Please let me know what further information/logs you need to track this down.

**Comment by slimjim777** [comment]
Seems to be up now. Can you send me the syslog from the serial-vault unit?

**Comment by paulgear** [comment]
I've grabbed all the logs and placed at https://private-fileshare.canonical.com/~paulgear/serial-vault-partners/serial-vault-logs.tar.xz

**Comment by slimjim777** [comment]
I've checked the syslog for 13 and 14th Feb and cannot see any reference to serial-vault restarting too quickly. The syslog has a *lot* of entries about nagios and livepatch restarting and I suspect that that is where the problem lies. This looks like a specific issue related to that particular deployment and not a charm issue, so I'll close this for now. If would be better to follow up through RT if there are further issues.
